# Generated by Django 4.2 on 2025-12-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Название заболевания")),
                ("description", models.TextField(verbose_name="Описание")),
                ("treatment", models.TextField(verbose_name="Лечение")),
                ("symptoms", models.JSONField(verbose_name="Симптомы")),
                ("severity", models.CharField(max_length=50, verbose_name="Степень серьезности")),
                ("specialist", models.CharField(max_length=100, verbose_name="Специалист")),
                ("category", models.CharField(max_length=100, verbose_name="Категория")),
            ],
            options={
                "verbose_name": "Заболевание",
                "verbose_name_plural": "Заболевания",
            },
        ),
    ]
