# Generated by Django 4.2 on 2025-12-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Название симптома")),
            ],
            options={
                "verbose_name": "Симптом",
                "verbose_name_plural": "Симптомы",
                "ordering": ["id"],
            },
        ),
    ]
